services:
  app:
    container_name: client_vue
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "80:80"
    # volumes:
    #   - ./:/app
    working_dir: /app
    command: http-server dist -p 80
    restart: unless-stopped

  web:
    container_name: immo-client-vue
    image: nginx:1.25
    ports:
      - "12345:80"
    volumes:
      - ./immo-client-vue.web:/usr/share/nginx/html:ro
    restart: unless-stopped
